SELECT * FROM USER;

SELECT * FROM PRODUCT;

SELECT COUNT(*) FROM PRODUCT;

SELECT MAX(PRICE) FROM PRODUCT;

SELECT MAX(PRICE), CODE, NAME FROM PRODUCT;

SELECT MIN(PRICE), CODE, NAME 
	FROM PRODUCT 
	WHERE NAME LIKE '%iP%';
	

SELECT MIN(PRICE) AS PRICE, CODE, NAME, 'MIN' AS PRICE_TYPE 
		FROM PRODUCT 
		WHERE NAME LIKE '%iP%'
UNION
SELECT MAX(PRICE) AS PRICE, CODE, NAME, 'MAX' AS PRICE_TYPE
		FROM PRODUCT 
		WHERE NAME LIKE '%iP%';
		
		
SELECT * FROM PURCHASE_ORDER;

SELECT CODE, NAME, PRICE FROM PRODUCT WHERE CODE=30

INSERT INTO PURCHASE_ORDER(USER_ID, PRODUCT_CODE, PRODUCT_PRICE, PRODUCT_QUANTITY)
VALUES (2, 24, 465, 2);

INSERT INTO PURCHASE_ORDER(USER_ID, PRODUCT_CODE, PRODUCT_PRICE, PRODUCT_QUANTITY)
VALUES (1, 30, (SELECT PRICE FROM PRODUCT WHERE CODE=30), 1);
