--<ScriptOptions statementTerminator=";"/>

ALTER TABLE PRODUCT DROP PRIMARY KEY;

ALTER TABLE USER_ADDRESS DROP PRIMARY KEY;

ALTER TABLE USER DROP PRIMARY KEY;

ALTER TABLE USER_ADDRESS DROP INDEX USER_ADDRESS_USER_FK;

DROP TABLE USER_ADDRESS;

DROP TABLE PRODUCT;

DROP TABLE USER;

CREATE TABLE USER_ADDRESS (
	ADDR_ID INT NOT NULL,
	STREET_ADDR VARCHAR(400),
	CITY CHAR(100),
	USER_ID INT,
	PRIMARY KEY (ADDR_ID)
) ENGINE=InnoDB;

CREATE TABLE PRODUCT (
	CODE INT NOT NULL,
	NAME CHAR(200) NOT NULL,
	PRICE DECIMAL(10 , 0) NOT NULL,
	DESCRIPTION VARCHAR(500),
	CRTD_TMS TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	PRIMARY KEY (CODE)
) ENGINE=InnoDB;

CREATE TABLE USER (
	USER_ID INT NOT NULL,
	FIRST_NAME CHAR(80) NOT NULL,
	LAST_NAME CHAR(100),
	EMAIL CHAR(250),
	CRTD_TMS TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	UPDT_TMS TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
	PHONE VARCHAR(40) NOT NULL,
	PRIMARY KEY (USER_ID)
) ENGINE=InnoDB;

CREATE INDEX USER_ADDRESS_USER_FK ON USER_ADDRESS (USER_ID ASC);

